[package]
name = "clarity-repl"
description = "Clarity REPL"
version = "0.10.0"
authors = ["Ludo Galabru <ludovic@galabru.com>"]
readme = "README.md"
edition = "2018"
license = "GPL-3.0-only"
keywords = ["blockstack", "blockchain", "clarity", "smart-contract", "repl"]
exclude = ["vs-client/**"]
homepage = "https://lgalabru.github.io/clarity-repl/"
repository = "https://github.com/lgalabru/clarity-repl"
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils"]

[dependencies]
ansi_term = "0.12.1"
lazy_static = "1.4.0"
regex = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.47", features = ["arbitrary_precision", "unbounded_depth"] }
sha2 = "0.9.3"
sha3 = "0.9.1"
serde_derive = "1.0"
ripemd160 = "0.9.1"
integer-sqrt = "0.1.3"
libsecp256k1 = "0.3.5"
serde_stacker = "0.1"
rand = "0.8.3"
atty = "0.2.14"
async-std = { version = "1.9.0", features = ["attributes"] }
reqwest = { version = "0.11", features = ["blocking", "json", "rustls"] }

# CLI
pico-args = { version = "0.4.0", optional = true }
rustyline = { version = "7.1.0", optional = true }
prettytable-rs = { version = "0.8.0", optional = true }

# WASM
wasm-bindgen = { version = "0.2", optional = true }

[lib]
name = "clarity_repl"
path = "src/lib.rs"
# Default type
# crate-type = ["lib"]

# Use this instead for WASM builds
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "clarity-repl"
path = "src/bin.rs"

[features]
default = ["cli"]
cli = ["pico-args", "rustyline", "prettytable-rs"]
wasm = ["wasm-bindgen"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false