[package]
name = "clarity-repl"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.0.0-beta.1", optional = true }
rustyline = { version = "6.1.2", optional = true }
ansi_term = "0.12.1"
lazy_static = "1.4.0"
regex = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.47"
sha2 = "0.8.1"
sha3 = "0.8.2"
serde_derive = "1.0"
ripemd160 = "0.8.0"
wasm-bindgen = { version = "0.2", optional = true }

[lib]
name = "clarity_repl"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "clarity-repl"
path = "src/bin.rs"

[features]
default = ["cli"]
cli = ["clap", "rustyline"]
wasm = ["wasm-bindgen"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false